### ISSUE TITLE
AngularJointDrive's InitialTarget causes oscillations or misplacement

### ISSUE THREAD

**Issue by jorgeolothar** [ExtendRealityLtd/Tilia.Interactions.Controllables.Unity#223]
### Pre-check

* Similar to https://github.com/ExtendRealityLtd/Tilia.Interactions.Controllables.Unity/issues/116, but with different setup

### Environment

* Code version: 2.6.2
* Platform version: 2021.3.17

### Steps to reproduce

Create a lever following the [Creating a Lever](https://github.com/ExtendRealityLtd/Tilia.Interactions.Controllables.Unity/tree/master/Documentation/HowToGuides/CreatingALever) tutorial.

Change the drive limit to -30 to 45
"Start at initial target" value 0.5

### Expected behavior

Lever starts at angle 7.5

### Current behavior

Lever is rotated at a different angle, and its position displaced
If you turn off the lever collider, it oscillates between two points instead

If you have a non-cube mesh (even with a box collider, but non-uniform) it also oscillates between two points, but more dramatically

**Comment by thestonefox** [comment]
Note: Only seems to break rotation on the joint drive, transform drive seems to work

**Comment by thestonefox** [comment]
ok so i think the issue is the initial drive speed is really high to make it seem like it snaps into position instantly, however that's causing the motor to never hit its target point because it infinitely overshoots

I think i have a fix by just slowing the motor down by half each frame until it reaches its destination.

**Comment by thestonefox** [comment]
![jointissue](https://user-images.githubusercontent.com/1029673/223977526-f171cd0e-5a72-423d-a1a1-b1dd69c7ee6f.gif)

here's the output of the above proposed fix

**Comment by thestonefox** [comment]
PR with proposed fix https://github.com/ExtendRealityLtd/Tilia.Interactions.Controllables.Unity/pull/224

**Comment by jorgeolothar** [comment]
Awesome, good call on the decaying force

**Comment by jorgeolothar** [comment]
Are the value change events active during this transition period? I'm concerned about the initial overshoot activating minValueReached or maxValueReached

**Comment by thestonefox** [comment]
> Are the value change events active during this transition period? I'm concerned about the initial overshoot activating minValueReached or maxValueReached

The events are not run when the initial movement is done, there's an option called `emit events` on the drive that is turned off during that move to start.
