### ISSUE TITLE
Issue with an image in "Creating A Physics Button"

### ISSUE THREAD

**Issue by fschmidmichels** [ExtendRealityLtd/Tilia.Interactions.Controllables.Unity#34]
It is admittetly a small issue, but I wasted like half an hour on it. Could you edit the image, so that the "Is Trigger" checkbox is shown as ticked? I was always looking at that image to find my error, only the image above it in the guide shows the checkbox as ticked. 

https://github.com/ExtendRealityLtd/Tilia.Interactions.Controllables.Unity/blob/master/Documentation/HowToGuides/CreatingAPhysicsButton/assets/images/DragCollisionTrackerIntoEvent.png

**Comment by extendreality** [comment]
https://github.com/ExtendRealityLtd/Tilia.Interactions.Controllables.Unity/pull/58
