### ISSUE TITLE
Show Min/Max/Mid reached event in drive's facade

### ISSUE THREAD

**Issue by fight4dream** [ExtendRealityLtd/Tilia.Interactions.Controllables.Unity#50]
## Is your feature request related to a problem?

We need to manually navigate the hierarchy to reach the min/max/mid reached event.

## Describe the solution you'd like

Show the min/max/mid reached event in the Linear/Rotation drive facade

## Additional context

Currently we need to navigate to these objects
![image](https://user-images.githubusercontent.com/22952143/87419217-b0b4da80-c605-11ea-8bfa-c5ec078754c3.png)

Want those to be presented on the facade
![image](https://user-images.githubusercontent.com/22952143/87419265-c5916e00-c605-11ea-8cee-793971bd4b8b.png)

**Comment by thestonefox** [comment]
There's a reason the min/mid/max don't get bubbled up to the facade. You may want multiple additional ones such as 25% of the way, 33% of the way, whatever. and you can't expose them all, so the best solution is to just have them as child events you can access.

This would also work well with the "Go To GameObject" component in the other ticket discussion (https://github.com/ExtendRealityLtd/Tilia.Interactions.Controllables.Unity/issues/49)
