### ISSUE TITLE
missing steps in doc Adding A Physical Button

### ISSUE THREAD

**Issue by fight4dream** [ExtendRealityLtd/Tilia.Interactions.Controllables.Unity#57]
the current guide has not yet set the source of the collider follower

should be inserted as Step 4

in the ActivationArea, add a NotifierContainerExtractor component,
in its Extracted event, +, drag in ColliderFollower, choose to call the method Source
![image](https://user-images.githubusercontent.com/22952143/88827664-d1338600-d1fc-11ea-80b0-be10afb39ba5.png)

back to CollisionTracker component,
in its CollisionStarted event, +, drag in ActivationArea, choose to call the method NotifierContainerExtractor.DoExtract
![image](https://user-images.githubusercontent.com/22952143/88827890-16f04e80-d1fd-11ea-9e88-edc89874430e.png)

**Comment by thestonefox** [comment]
This isn't actually the best way of doing this, if both controllers are in the zone then the collider follower will only follow the one controller.

The guide will be updated with a more appropriate solution.

**Comment by extendreality** [comment]
https://github.com/ExtendRealityLtd/Tilia.Interactions.Controllables.Unity/pull/58
