### ISSUE TITLE
Request for increment snapping

### ISSUE THREAD

**Issue by CraigASanford** [ExtendRealityLtd/Tilia.Interactions.Controllables.Unity#79]
## Is your feature request related to a problem?

No

## Describe the solution you'd like

VRTK V3 controls has a snapping features. Sliders and rotators could snap to increments rather than moving smoothly. Think of it more like "clicking" from one position to another. I'd love to see the AngularJointDrive and LinearJointDrive have this feature.

## Describe alternatives you've considered

Custom scripting this is definitely a possibility but I think the use case for this feature is probably common enough to warrant it being a normal option.

**Comment by thestonefox** [comment]
This is already implemented using the step values
